package cse213.todayjava.Milad.UserSecurityPersonnel;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import cse213.todayjava.User;

public class SecurityPersonnel extends User{
    private int personnelID;
    private String name;
    private String zoneAssigned;
    private String shiftTime;

    public SecurityPersonnel(String userid, String userType, int personnelID, String name, String zoneAssigned, String shiftTime) {
        super(userid, userType);
        this.personnelID = personnelID;
        this.name = name;
        this.zoneAssigned = zoneAssigned;
        this.shiftTime = shiftTime;
    }

    public int getPersonnelID() {
        return personnelID;
    }

    public void setPersonnelID(int personnelID) {
        this.personnelID = personnelID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getZoneAssigned() {
        return zoneAssigned;
    }

    public void setZoneAssigned(String zoneAssigned) {
        this.zoneAssigned = zoneAssigned;
    }

    public String getShiftTime() {
        return shiftTime;
    }

    public void setShiftTime(String shiftTime) {
        this.shiftTime = shiftTime;
    }

    public Boolean loginToDashboard(String credentials) {
        System.out.println("Security personnel " + name + " attempting to login...");
        return credentials != null && !credentials.trim().isEmpty();
    }

    public Boolean selectPatrolZone(String zoneId) {
        System.out.println("Security personnel " + name + " selected patrol zone: " + zoneId);
        return zoneId != null && !zoneId.trim().isEmpty();
    }

    public Boolean logShiftStart() {
        System.out.println("Security personnel " + name + " started shift at " + LocalDateTime.now());
        return true;
    }

    public Boolean logShiftEnd() {
        System.out.println("Security personnel " + name + " ended shift at " + LocalDateTime.now());
        return true;
    }

    public Boolean openTicketValidation() {
        System.out.println("Opening ticket validation interface for " + name);
        return true;
    }

    public Boolean verifyMediaCredential(String promoterId) {
        System.out.println("Verifying media credential for promoter: " + promoterId);
        return promoterId != null && promoterId.startsWith("MEDIA");
    }

    public Boolean acknowledgeIncidentAlert(String incidentId) {
        System.out.println("Security personnel " + name + " acknowledged incident: " + incidentId);
        return incidentId != null && !incidentId.trim().isEmpty();
    }

    public String generateIncidentReport(Map<String, String> filters) {
        System.out.println("Generating incident report with filters: " + filters);
        return "Incident Report generated by " + name + " with filters: " + filters;
    }

    public Boolean addToWatchlist(Map<String, String> personDetails) {
        System.out.println("Adding person to watchlist: " + personDetails);
        return personDetails != null && !personDetails.isEmpty();
    }

    @Override
    public String toString() {
        return "SecurityPersonnel{" +
                "personnelID=" + personnelID +
                ", name='" + name + '\'' +
                ", zoneAssigned='" + zoneAssigned + '\'' +
                ", shiftTime='" + shiftTime + '\'' +
                '}';
    }
}
